spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://207.148.120.72:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog
    password: EbRBBra6tY6byBfW
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    me.kamikid: info
  file: log/blog-dist.log